
services:
  datanode:
    container_name: datanode
    depends_on:
      - namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - hadoop_datanode:/hadoop/dfs/data

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    command: start-notebook.sh --NotebookApp.token=''
    container_name: jupyter
    depends_on:
      - spark-master
    image: custom-pyspark-notebook
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work

  namenode:
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    ports:
      - 50070:50070
      - 8020:8020
    volumes:
      - hadoop_namenode:/hadoop/dfs/name

  spark-master:
    container_name: spark-master
    depends_on:
      - namenode
      - datanode
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MODE=master
    image: bde2020/spark-master:2.4.0-hadoop2.7
    ports:
      - 7077:7077
      - 8080:8080
    volumes:
      - ./jobs:/opt/spark-jobs

  spark-worker:
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    ports:
      - 8081:8081

volumes:
  hadoop_datanode: null
  hadoop_namenode: null
